### ISSUE TITLE
[iOS 18] App crashes/closes whenever I scroll the list

### ISSUE THREAD

**Issue by marcosmoura** [joeldavidw/Chronos#47]
I'm not sure if this is an issue with iOS 18 or if it happens on 17 as well. 

This only happens when the **"Tap to review"** feature is off.

## Steps to reproduce:
- Open app
- Scroll the main view
- App crashes and closes

## Also happens when:
- Open app
- Change the sorting to anything 
- App crashes and closes

My suspicion is that whenever the list refreshes the application crashes, but unfortunately I cannot debug and confirm this.

For me, this is a blocker to use, but I appreciate all of your work and have high hopes for the future of the app though! :)

**Comment by joeldavidw** [comment]
Does this still happen in the latest iOS beta (Developer Beta 4/Public Beta 2)?

**Comment by marcosmoura** [comment]
Yes, it is. Latest iOS 18 beta with latest Chronos version. 

With the search feature, I can now use the app if instead of scrolling I just search.

**Comment by joeldavidw** [comment]
I was unable to replicate the issue, even with 100 mock tokens. However, I am working on optimization for the Token view, which may solve this problem.

**Comment by joeldavidw** [comment]
Hey @marcosmoura, v11.0 with the optimizations has been released. Could you test it out and see whether it is still crashing for you?

**Comment by marcosmoura** [comment]
@joeldavidw 
The issue still persists. Since iOS 18 is no longer in beta, it might be easier to test now.
Let me know if you need more information to debug the issue.

**Comment by marcosmoura** [comment]
This also happens on the iPhone 16 and 16 pro

**Comment by joeldavidw** [comment]
I discovered a bug where tokens are being regenerated too frequently: https://github.com/joeldavidw/Chronos/pull/68. I’m still not certain if this will resolve the issue entirely. 

~~Do you have any non-default tokens (e.g., duration other than 30 seconds, algorithm not equal to SHA-1)?~~

~~Could you also try:~~
~~1. Export your current vault~~
~~2. Verify that export works~~
~~3. Start create a new vault and import https://gist.github.com/joeldavidw/dd3ab8cfbd58c0e3962642c661f5c4ae~~
~~4. Verify if it still crashes~~

**Comment by joeldavidw** [comment]
@marcosmoura I think I may have found the issue. It doesn’t seem to be performance-related but might be due to **invalid token** parameters.

Here is the related PR: https://github.com/joeldavidw/Chronos/pull/71

I hope this resolves the problem 🙏

Released in v15

**Comment by joeldavidw** [comment]
Hey @marcosmoura, I’ll close this for now. If the issue persists after updating to v15, just leave a comment, and we’ll reopen it.
